import { ResourcePageConfig } from '../../shared/resource-crud/resource-page.types';

export const productosPageConfig: ResourcePageConfig = {
  key: 'productos',
  idKey: 'idProducto',
  title: 'Productos',
  description: 'Gestiona medicamentos y productos de cuidado con categoria, proveedor y vencimiento.',
  createLabel: 'producto',
  emptyState: 'Todavia no hay productos en catalogo.',
  searchableFields: ['nombre', 'codigoBarras', 'descripcion'],
  columns: [
    { key: 'nombre', label: 'Producto' },
    { key: 'codigoBarras', label: 'Codigo' },
    { key: 'precioVenta', label: 'Venta', type: 'currency' },
    { key: 'precioCompra', label: 'Compra', type: 'currency' },
    { key: 'idCategoria', label: 'Categoria', type: 'lookup', lookup: { resource: 'categorias', labelKey: 'nombre', valueKey: 'idCategoria' } },
    { key: 'idProveedor', label: 'Proveedor', type: 'lookup', lookup: { resource: 'proveedores', labelKey: 'nombre', valueKey: 'idProveedor' } },
    { key: 'requiereReceta', label: 'Receta', type: 'boolean' },
    { key: 'fechaVencimiento', label: 'Vencimiento', type: 'date' },
  ],
  fields: [
    { key: 'nombre', label: 'Nombre', type: 'text', required: true, maxLength: 200 },
    { key: 'codigoBarras', label: 'Codigo de barras', type: 'text', required: true, maxLength: 50 },
    { key: 'descripcion', label: 'Descripcion', type: 'textarea', maxLength: 500 },
    {
      key: 'precioVenta',
      label: 'Precio de venta',
      type: 'currency',
      required: true,
      min: 0.01,
      integerDigits: 8,
      fractionDigits: 2,
      step: '0.01',
    },
    {
      key: 'precioCompra',
      label: 'Precio de compra',
      type: 'currency',
      required: true,
      min: 0.01,
      integerDigits: 8,
      fractionDigits: 2,
      step: '0.01',
    },
    { key: 'idCategoria', label: 'Categoria', type: 'select', required: true, lookup: { resource: 'categorias', labelKey: 'nombre', valueKey: 'idCategoria' } },
    { key: 'idProveedor', label: 'Proveedor', type: 'select', required: true, lookup: { resource: 'proveedores', labelKey: 'nombre', valueKey: 'idProveedor' } },
    { key: 'requiereReceta', label: 'Requiere receta', type: 'checkbox' },
    { key: 'fechaVencimiento', label: 'Fecha de vencimiento', type: 'date' },
  ],
};
