import { ResourcePageConfig } from '../../shared/resource-crud/resource-page.types';

export const clientesPageConfig: ResourcePageConfig = {
  key: 'clientes',
  idKey: 'idCliente',
  title: 'Clientes y pacientes',
  description: 'Registra la base comercial de compradores y pacientes frecuentes.',
  createLabel: 'cliente',
  emptyState: 'Todavía no hay clientes creados.',
  searchableFields: ['nombre', 'apellido', 'dni', 'telefono', 'email'],
  pagination: {
    enabled: true,
    pageSize: 5,
    pageSizeOptions: [5, 10, 15, 20, 50],
    sortBy: 'idCliente',
    direction: 'asc',
  },
  importExport: {
    enabled: true,
    defaultFormat: 'excel',
    formats: ['excel', 'csv'],
  },
  columns: [
    { key: 'nombre', label: 'Nombre' },
    { key: 'apellido', label: 'Apellido' },
    { key: 'dni', label: 'DNI' },
    { key: 'telefono', label: 'Telefono' },
    { key: 'email', label: 'Correo' },
  ],
  fields: [
    {
      key: 'nombre',
      label: 'Nombre',
      type: 'text',
      required: true,
      maxLength: 100,
      inputFilter: 'lettersSpaces',
      pattern: '^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$',
      helpText: 'Solo admite letras y espacios.',
    },
    {
      key: 'apellido',
      label: 'Apellido',
      type: 'text',
      required: true,
      maxLength: 100,
      inputFilter: 'lettersSpaces',
      pattern: '^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$',
      helpText: 'Solo admite letras y espacios.',
    },
    {
      key: 'dni',
      label: 'DNI',
      type: 'text',
      inputFilter: 'digits',
      maxLength: 8,
      minLength: 8,
      pattern: '^\\d{8}$',
      helpText: 'Solo admite 8 digitos numericos.',
    },
    {
      key: 'telefono',
      label: 'Telefono',
      type: 'text',
      inputFilter: 'digits',
      maxLength: 9,
      minLength: 9,
      pattern: '^\\d{9}$',
      helpText: 'Solo admite 9 digitos numericos.',
    },
    {
      key: 'email',
      label: 'Correo',
      type: 'email',
      maxLength: 150,
      pattern: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
      helpText: 'Usa la estructura usuario@organizacion.dominio.',
    },
  ],
};
